worker_processes 1;

events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream
    
    types {
        text/plain c cpp cs go java js lua pl cgi py rb ru rs swift md json sh yaml yml xml css html;
    }

    server {
        listen 80;
	server_name localhost;

	location /static/ {
	    alias /usr/share/nginx/html/static/;
	    autoindex on;
	}
    }
}
