worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    types {
        text/plain c cpp cs go java lua cgi py rb ru rs swift md sh yaml yml;
    }

    server {
        listen 80;
        server_name localhost;

        location /static/ {
            alias /usr/share/nginx/html/static/;
            autoindex on;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
            add_header 'Access-Control-Max-Age' 1728000 always;

            # Responder bien a OPTIONS sin usar 'if'
            if ($request_method = OPTIONS) {
                return 204;
            }
        }
    }
}