INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('C', 'c', 1, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('C++', 'cpp', 2, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('C#', 'cs', 3, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Go', 'go', 4, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Java', 'java',5, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('JavaScript', 'js', 6, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Lua', 'lua', 7, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Perl', 'pl', 8, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Python', 'py', 9, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Ruby', 'rb', 10, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Rust', 'rs', 11, 1);
INSERT INTO supportedlang(lang_name, lang_extension, icon_id, version) VALUES ('Swift', 'swift', 12, 1);
